
name: dupfile_apk
description: "A duplicate file finder application with modern UI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  file_picker: ^8.3.2
  crypto: ^3.0.3
  path_provider: ^2.1.2
  path: ^1.9.0
  url_launcher: ^6.2.5
  open_filex: ^4.0.2
  sqflite: ^2.3.2+1
  sqflite_common_ffi: ^2.3.0+4
  permission_handler: ^11.3.1
  intl: ^0.18.0
  android_intent_plus: ^4.0.3
  share_plus: ^7.2.2
  device_info_plus: ^9.1.2
  desktop_drop: ^0.4.4
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# iOS specific configuration
ios:
  deployment_target: '12.0'
